### PR TITLE
remove lodash

### PR DESCRIPTION
**Pull request by lukeed**
Hi there 👋 

`lodash` is a huge dependency & you were using a tiny portion of it. Really you just needed `snakeCase` -- the rest were native stand-ins w/ a `lodash.` prefix.

Ran tests locally & all were passing

### CODE REVIEW

**Comment by danbillson** [comment]
Hey @lukeed 👋 

Thanks for your contribution! We'll review your change and get back to you shortly

**Review by danbillson — APPROVED** [review]

**Comment by danbillson** [comment]
Hey @lukeed 

I'm happy with the changes you've made but we require all commits to be signed before merging, it might be possible to sign the older commit with something like
```
git rebase --signoff HEAD~2
```

**Comment by lukeed** [comment]
Sorry for the delay.

I ran the command, which doesn't seem to have done anything which is odd considering my others elsewhere are signed. 
It may be because I did this PR inside a Codespace...?

I'm totally fine/happy if you'd rather cherry-pick the diffs. It's not an involved PR and I'd rather see this not get caught up in process-like things, especially when its my own doing 🙃

**Comment by lukeed** [comment]
Fixed. I was on a machine that didnt have a GPG configured 🤦

**Comment by danbillson** [comment]
Great, thanks for your contribution here @lukeed this should give us a huge saving on bundle size

**Pull request merged**
